### ISSUE TITLE
Kissim error at "Encoding" stage

### ISSUE THREAD

**Issue by catsantos88** [volkamerlab/cicag_klifs_workshop#2]
Hi there! 

I love this notebook and I was able to run it in the past several times, which provided valuable information.

Coming back to it this week I don't seem to be able to load Kissim as I get the error attached. My best guess is that some packages might have been updated and now some of the dependencies are broken.

I would love to be able to run it again!

Many thanks for all your valuable contributions.

Catarina Santos

![Screenshot 2022-11-18 at 16 20 59](https://user-images.githubusercontent.com/118554002/202752552-b7dc1e2b-5b9b-4060-a338-079ddefe73d6.png)

**Comment by dominiquesydow** [comment]
Hi @catsantos88,

Very happy to hear this notebook is useful to your work! :)

Thanks a lot for raising this issue. I fixed this with an update in the environment file (see #3). 
Could you please install a fresh `conda` environment from this file? 
If it still causes problems, please reopen this issue, thank you!

**Comment by dominiquesydow** [comment]
I also fixed a broken URL in the notebook (see https://github.com/volkamerlab/cicag_klifs_workshop/commit/a0d9681ce35837aa18dc7cca56c029ecf10411ac) - letting you know here just in case you run into conflicts when pulling the latest repo changes into your local copy.
